server: #chiếm server
  port: 8080
  servlet:
    context-path: /hotel-management #url mặc định
spring:
  application:
    name: hotel-management
  datasource: #mng tạo db nhé
    url: "jdbc:mysql://localhost:3306/hotel_test"
    username: root
    password: "@Giangloen123"
  jpa: #tự thay đổi trong db
    hibernate:
      ddl-auto: update
    show-sql: true
